# Generated by Django 3.1.2 on 2020-11-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0003_auto_20201113_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='orders',
                                    to='profiles.userprofile'),
        ),
    ]
