# Generated by Django 3.1.2 on 2020-11-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seasonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
